# This is a basic workflow to help you get started with Actions
name: GitHub Actions - cron test



on:
  push:
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest



   steps:
      - name: Run a one-line script
        run: echo This is my test!
      - name: Again a one-line script
        run: echo TEST!